import {armFixture} from './armed-fixture.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Game} from '../src/simulation/game.js';
import {Combat} from '../src/simulation/combat.js';
import {Character} from '../src/domain/character/character.js';
import {createEnemies} from '../src/domain/enemies/spawns.js';
import {EnemyAI} from '../src/simulation/enemy-ai.js';
import {AI_CONFIG as A} from '../src/domain/enemies/config.js';
import {canStand} from '../src/world/collision.js';
import {resolvePlayerBodies,separateBodies} from '../src/simulation/bodies.js';
const plain=()=>({bounds:{minX:-20,maxX:20,minZ:-20,maxZ:20},spawn:{x:0,z:0},portal:{x:15,z:15,interactRadius:1},obstacles:[]});
const spawn=(id,x,z,overrides={})=>({id,enemyType:'trainingSlime',position:{x,z},overrides});
function setup(spawns=[spawn('one',3,0)],world=plain()){
  const game=new Game(world),character=new Character(),enemies=createEnemies(spawns,world),combat=new Combat(game,character,{enemies,random:()=>.5});armFixture(character);combat.ai=new EnemyAI(combat);return {game,character,combat,ai:combat.ai,enemies,e:enemies[0]};
}
function run(s,seconds,fps=60,axis={x:0,z:0}){for(let i=0;i<Math.round(seconds*fps);i++)s.combat.update(1/fps,axis,0);}
const place=(s,x,z)=>{s.game.cancel();Object.assign(s.game.player,{x,z,moving:false});s.game.previous={...s.game.player};};
test('data-driven spawns have independent identity, origin, statistics and timers',()=>{const s=setup([spawn('one',3,0),spawn('two',-3,0)]);s.e.x=2;s.e.stats.maxHP=90;assert.equal(s.e.spawnPosition.x,3);assert.equal(s.enemies[1].stats.maxHP,120);assert.notEqual(s.e.ai,s.enemies[1].ai);assert.throws(()=>setup([spawn('a',2,0),spawn('a',3,0)]));});
test('perception acquires a living visible player with an aggro reason',()=>{const s=setup();run(s,.19);assert.equal(s.e.targetId,s.character.data.id);assert.equal(s.e.aggroReason,'perception');assert.equal(s.e.state,'alert');});
test('outside detection, passive enemies and dead player do not trigger perception',()=>{for(const s of [setup([spawn('a',8,0)]),setup([spawn('a',2,0,{aggressive:false})])]){run(s,1);assert.equal(s.e.state,'idle');assert.equal(s.e.targetId,null);}const s=setup();s.character.damage(999);run(s,.5);assert.equal(s.e.targetId,null);});
test('solid obstacles block perception when LOS is required',()=>{const world=plain();world.obstacles=[{shape:'rect',x:1.5,z:0,halfX:.2,halfZ:2}];const s=setup([spawn('a',3,0)],world);run(s,1);assert.equal(s.e.state,'idle');s.e.requiresLOS=false;run(s,.3);assert.equal(s.e.targetId,s.character.data.id);});
test('chase reaches attack range and uses existing attack damage',()=>{const s=setup();run(s,2);assert.equal(s.e.state,'attacking');assert.ok(s.combat.distance(s.e)<=s.e.stats.attackRange);assert.ok(s.character.data.hp<160);});
test('leaving attack range cancels impact and resumes chase',()=>{const s=setup();run(s,1.2);const hp=s.character.data.hp;place(s,-3,0);run(s,.2);assert.equal(s.e.state,'chasing');assert.equal(s.character.data.hp,hp);assert.ok(s.e.path.length);});
test('enemy navigation routes around solid obstacles instead of crossing them',()=>{const world=plain();world.obstacles=[{shape:'rect',x:1.5,z:0,halfX:.3,halfZ:1}];const s=setup([spawn('a',3,0,{requiresLOS:false,detectionRange:5})],world);for(let i=0;i<240;i++){run(s,1/60);assert.ok(canStand(world,s.e.x,s.e.z,s.e.radius));}assert.equal(s.e.state,'attacking');});
test('repath is throttled and reacts to significant target movement',()=>{const s=setup([spawn('a',6,0,{detectionRange:9,chaseSpeed:1})]);run(s,.8);const paths=s.ai.metrics.paths;place(s,0,2);run(s,.6);assert.ok(s.ai.metrics.paths>paths);assert.ok(s.ai.metrics.paths<15);});
test('small leash boundary excursion does not immediately reset aggro',()=>{const s=setup();run(s,.5);place(s,s.e.spawnPosition.x-s.e.leashRange-.7,0);run(s,.3);assert.equal(s.e.state,'chasing');place(s,-3,0);run(s,.2);assert.equal(s.e.ai.outside,0);});
test('sustained leash violation clears target, enters return and stops attacks',()=>{const s=setup();run(s,1);place(s,-10,0);run(s,1.1);assert.equal(s.e.state,'returning');assert.equal(s.e.targetId,null);assert.notEqual(s.combat.enemyCycles.get(s.e.id).phase,'windup');});
test('return regenerates gradually and fills HP on arrival without normal teleport',()=>{const s=setup([spawn('a',5,0)]);s.e.x=0;s.e.hp=20;s.ai.returning(s.e,'test');place(s,-10,0);run(s,.1);assert.ok(s.e.hp>20&&s.e.hp<120);assert.ok(s.e.x>0&&s.e.x<1);run(s,2);assert.equal(s.e.state,'idle');assert.equal(s.e.hp,120);assert.ok(Math.abs(s.e.x-5)<A.spawnArrival);assert.equal(s.ai.metrics.fallbacks,0);});
test('returning ignores damage and reacquisition to prevent leash exploits',()=>{const s=setup();s.e.x=0;s.e.hp=50;s.ai.returning(s.e,'test');s.e.damage(10);s.ai.onDamaged(s.e,s.character.data.id);assert.equal(s.e.hp,50);assert.equal(s.e.targetId,null);assert.equal(s.combat.select(s.e.id),false);});
test('aggro is individual and does not socially alert distant neighbors',()=>{const s=setup([spawn('near',2,0),spawn('far',8,0),spawn('passive',-2,0,{aggressive:false})]);run(s,.3);assert.equal(s.e.targetId,s.character.data.id);assert.equal(s.enemies[1].targetId,null);assert.equal(s.enemies[2].targetId,null);s.ai.onDamaged(s.enemies[2],s.character.data.id);assert.equal(s.enemies[2].aggroReason,'damage');assert.equal(s.enemies[1].targetId,null);});
test('all six eligible enemies can acquire aggro without a global cap',()=>{const spawns=Array.from({length:6},(_,i)=>spawn('s'+i,Math.sin(i*Math.PI/3)*2.5,Math.cos(i*Math.PI/3)*2.5));const s=setup(spawns);run(s,.4);assert.equal(s.enemies.filter(e=>e.targetId===s.character.data.id).length,6);});
test('individual death removes only its body/target and starts respawn',()=>{const s=setup([spawn('a',3,0),spawn('b',-3,0)]);s.combat.select(s.e.id);s.e.damage(999);run(s,.1);assert.equal(s.e.state,'dead');assert.equal(s.combat.currentTarget,null);assert.ok(s.enemies[1].alive);run(s,1.6);assert.equal(s.e.state,'respawning');assert.equal(s.character.data.xp,0);});
test('respawn restores source position, HP and clean attack state',()=>{const s=setup([spawn('a',6,0,{respawnTime:2})]);s.e.x=5;s.e.damage(999);run(s,2.1);assert.equal(s.e.state,'idle');assert.equal(s.e.hp,120);assert.equal(s.e.x,6);assert.equal(s.e.targetId,null);assert.equal(s.e.path.length,0);assert.equal(s.e.generation,1);});
test('respawn is delayed when player or another body occupies origin',()=>{const s=setup([spawn('a',3,0,{respawnTime:2})]);s.e.damage(999);place(s,3,0);run(s,3);assert.equal(s.e.state,'respawning');place(s,-5,0);run(s,.6);assert.ok(s.e.alive);const t=setup([spawn('a',3,0,{respawnTime:2}),spawn('b',6,0,{aggressive:false})]);t.e.damage(999);t.enemies[1].x=3;run(t,3);assert.equal(t.e.state,'respawning');});
test('player death clears all aggro and pending impacts while enemies return',()=>{const s=setup([spawn('a',2,0),spawn('b',-2,0)]);run(s,.8);s.character.damage(999);run(s,.1);assert.equal(s.combat.state,'dead');assert.ok(s.enemies.every(e=>e.targetId===null));assert.ok(s.enemies.every(e=>['returning','idle'].includes(e.state)));const resultCount=s.combat.events.filter(e=>e.source==='enemy').length;run(s,1);assert.equal(s.combat.events.filter(e=>e.source==='enemy').length,resultCount);assert.ok(s.enemies.some(e=>e.state==='idle'));});
test('pause freezes perception, movement, respawn and attacks together',()=>{const s=setup([spawn('a',3,0),spawn('b',-3,0)]);run(s,.5);s.enemies[1].damage(999);s.game.paused=true;const snapshot=JSON.stringify(s.enemies);run(s,10);assert.equal(JSON.stringify(s.enemies),snapshot);});
test('impossible chase transitions into return with a bounded pathfinding count',()=>{const world=plain();world.obstacles=[{shape:'rect',x:1.5,z:0,halfX:.2,halfZ:20}];const s=setup([spawn('a',3,0,{requiresLOS:false,detectionRange:5})],world);run(s,3);assert.ok(['idle','returning'].includes(s.e.state));assert.ok(s.ai.metrics.paths<60);assert.ok(canStand(world,s.e.x,s.e.z,s.e.radius));});
test('blocked return uses safe fallback only after stuck timeout',()=>{const world=plain(),s=setup([spawn('a',6,0)],world);s.e.x=2;s.ai.returning(s.e,'test');world.obstacles.push({shape:'rect',x:4,z:0,halfX:.2,halfZ:20});run(s,1);assert.equal(s.ai.metrics.fallbacks,0);run(s,2);assert.equal(s.ai.metrics.fallbacks,1);assert.equal(s.e.x,6);assert.equal(s.e.state,'idle');});
test('separation resolves coincident bodies and respects static walls',()=>{const s=setup([spawn('a',3,0),spawn('b',3,0),spawn('c',3,0)]);for(let i=0;i<120;i++)separateBodies(s.game.world,s.enemies,null,1/60);for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)assert.ok(Math.hypot(s.enemies[i].x-s.enemies[j].x,s.enemies[i].z-s.enemies[j].z)>.95);});
test('player movement contacts and pushes a body instead of walking through it',()=>{const s=setup([spawn('a',1,0,{aggressive:false})]);run(s,.4,60,{x:1,z:0});assert.ok(s.e.x>1);assert.ok(s.game.player.x<s.e.x);assert.ok(s.combat.distance(s.e)>=.79);});
test('swept collision blocks a high displacement from tunneling through a pinned enemy',()=>{const s=setup([spawn('a',2,0,{aggressive:false})]);s.game.world.obstacles.push({shape:'rect',x:3,z:0,halfX:.3,halfZ:3});s.game.previous={...s.game.player};s.game.player.x=2.8;resolvePlayerBodies(s.game,s.enemies);assert.ok(s.game.player.x<s.e.x);assert.ok(canStand(s.game.world,s.e.x,s.e.z,s.e.radius));});
test('AI and attack outcomes remain comparable at 30, 60 and 144 FPS',()=>{const results=[];for(const fps of [30,60,144]){const s=setup();run(s,3,fps);results.push(s);assert.equal(s.e.state,'attacking');}assert.ok(Math.max(...results.map(s=>s.e.x))-Math.min(...results.map(s=>s.e.x))<.1);assert.equal(new Set(results.map(s=>s.character.data.hp)).size,1);});
test('normal and twenty-enemy Hub fixtures validate; scale run stays finite with bounded repaths',()=>{const world=JSON.parse(readFileSync(new URL('../src/data/hub.json',import.meta.url))),normal=JSON.parse(readFileSync(new URL('../src/data/enemy-spawns.json',import.meta.url))),stress=JSON.parse(readFileSync(new URL('../src/data/enemy-spawns-stress.json',import.meta.url)));assert.equal(createEnemies(normal,world).length,6);assert.equal(stress.length,20);const s=setup(stress,world);s.character.modifiers.other={stats:{maxHP:100000}};s.character.recalculate();s.character.restoreHP();place(s,0,-2);const start=performance.now();run(s,15);const elapsed=performance.now()-start;for(const e of s.enemies){assert.ok(Number.isFinite(e.x+e.z+e.hp));assert.ok(canStand(world,e.x,e.z,e.radius));}assert.ok(s.ai.metrics.paths<2500);console.log('20 enemies / 15 simulated seconds:',elapsed.toFixed(1),'ms, paths:',s.ai.metrics.paths,'fallbacks:',s.ai.metrics.fallbacks);});

test('twenty simultaneous pursuers remain independent with bounded navigation work',()=>{const spawns=Array.from({length:20},(_,i)=>spawn('crowd-'+i,Math.sin(i*Math.PI/10)*3.5,Math.cos(i*Math.PI/10)*3.5,{detectionRange:4.5})),s=setup(spawns);s.character.modifiers.other={stats:{maxHP:100000}};s.character.recalculate();s.character.restoreHP();run(s,.4);assert.equal(s.enemies.filter(e=>e.targetId===s.character.data.id).length,20);const start=performance.now();for(let i=0;i<600;i++){if(i%120===0)place(s,Math.sin(i/120)*1.8,Math.cos(i/120)*1.8);s.combat.update(1/60,{x:0,z:0},0);}console.log('20 active pursuers / 10 simulated seconds:',(performance.now()-start).toFixed(1),'ms, paths:',s.ai.metrics.paths);assert.ok(s.ai.metrics.paths<600);assert.ok(s.enemies.every(e=>e.alive&&Number.isFinite(e.x+e.z)));assert.ok(s.character.data.hp<100000);for(let i=0;i<20;i++)for(let j=i+1;j<20;j++)assert.ok(Math.hypot(s.enemies[i].x-s.enemies[j].x,s.enemies[i].z-s.enemies[j].z)>.6);});
test('return fallback waits instead of teleporting onto player',()=>{const world=plain(),s=setup([spawn('a',6,0)],world);s.e.x=2;s.ai.returning(s.e,'test');world.obstacles.push({shape:'rect',x:4,z:0,halfX:.2,halfZ:20});place(s,6,0);run(s,4);assert.equal(s.ai.metrics.fallbacks,0);assert.equal(s.e.state,'returning');place(s,8,3);run(s,.2);assert.equal(s.ai.metrics.fallbacks,1);});
import * as THREE from 'three';
import {CombatVisual} from '../src/adapters/rendering/combat-visual.js';
test('ray targeting distinguishes nearby monsters and draws only the selected ring',()=>{const s=setup([spawn('left',-1,0),spawn('right',1,0)]),camera=new THREE.OrthographicCamera(-8,8,6,-6,.1,100);camera.position.set(0,15,15);camera.lookAt(0,.4,0);camera.updateMatrixWorld();const view={scene:new THREE.Scene(),camera,raycaster:new THREE.Raycaster(),canvas:{getBoundingClientRect:()=>({left:0,top:0,width:800,height:600})},selection:{material:{color:new THREE.Color()}}},visual=new CombatVisual(view,s.combat);for(const e of s.enemies){const point=new THREE.Vector3(e.x,.43,e.z).project(camera);assert.equal(visual.pick((point.x+1)*400,(1-point.y)*300),e.id);s.combat.select(e.id);visual.update();assert.equal([...visual.models.values()].filter(m=>m.ring.visible).length,1);assert.ok(visual.models.get(e.id).ring.visible);}view.scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});});

test('a surrounded player can push through a small group without remaining trapped',()=>{const spawns=Array.from({length:5},(_,i)=>spawn('ring-'+i,Math.sin(i*Math.PI*2/5)*1.05,Math.cos(i*Math.PI*2/5)*1.05,{aggressive:false})),s=setup(spawns);run(s,2,60,{x:1,z:0});assert.ok(s.game.player.x>4);assert.ok(s.enemies.every(e=>s.combat.distance(e)>=.79));});
