import {armFixture} from './armed-fixture.js';
import {Inventory} from '../src/domain/items/inventory.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/simulation/game.js';
import {Combat} from '../src/simulation/combat.js';
import {Character} from '../src/domain/character/character.js';
import {Enemy} from '../src/domain/combat/enemy.js';
import {AbilityRuntime} from '../src/simulation/abilities.js';
import {ABILITIES,INITIAL_HOTBAR,validateAbility} from '../src/domain/abilities/definitions.js';
import {PeriodicEffects,Projectiles} from '../src/domain/abilities/effects.js';
import {decodeSave,encodeSave} from '../src/adapters/persistence/character-save.js';
function setup(weapon='sword',x=1.2){const world={bounds:{minX:-20,maxX:20,minZ:-20,maxZ:20},spawn:{x:0,z:0},portal:{x:15,z:15,interactRadius:1},obstacles:[]},game=new Game(world),character=new Character(),enemy=new Enemy();enemy.x=x;enemy.z=0;// Isolate ability formulas from equipment bonuses; acquisition is tested in the RPG loop suite.
character.data.knownAbilities=Object.keys(ABILITIES);armFixture(character,weapon);const combat=new Combat(game,character,{enemies:[enemy],random:()=>.5});combat.retaliation=false;combat.currentTarget=enemy.id;combat.abilities=new AbilityRuntime(combat);return {world,game,character,enemy,combat,r:combat.abilities};}
function run(s,seconds,fps=120,axis={x:0,z:0}){for(let i=0;i<Math.round(seconds*fps);i++)s.combat.update(1/fps,axis,0);}
test('ability definitions validate and hotbar contains five techniques and three empty slots',()=>{assert.equal(INITIAL_HOTBAR.length,8);assert.equal(INITIAL_HOTBAR.filter(Boolean).length,5);for(const a of Object.values(ABILITIES))assert.equal(validateAbility(a),a);assert.throws(()=>validateAbility({...ABILITIES.powerStrike,manaCost:-1}));assert.throws(()=>validateAbility({...ABILITIES.doubleShot,effects:[{type:'projectile',at:0,power:1,speed:0}]}));});
test('wrong weapons, empty slots and unknown skills never spend MP or start cooldown',()=>{const s=setup();for(const slot of [2,3,4,6,7,8])assert.equal(s.r.request(slot),false);assert.equal(s.character.data.mp,80);assert.equal(s.r.cooldowns.size,0);s.character.data.knownAbilities=[];assert.equal(s.r.request(1),false);});
test('each weapon permits its technique and all weapons permit Regeneration',()=>{for(const [i,w] of ['sword','dagger','bow','staff'].entries()){const s=setup(w);assert.equal(s.r.request(i+1),true);assert.equal(s.r.request(5),true);assert.equal(s.character.data.classId,'novice');}});
test('cost and cooldown commit once only when valid execution begins',()=>{const s=setup();s.r.request(1);assert.equal(s.character.data.mp,80);assert.equal(s.r.remaining('powerStrike'),0);run(s,.1);assert.equal(s.character.data.mp,72);assert.ok(s.r.remaining('powerStrike')>3.8);assert.equal(s.r.metrics.started,1);run(s,.2);assert.equal(s.character.data.mp,72);assert.equal(s.r.request(1),false);});
test('insufficient MP and invalid target reject without a charge',()=>{const s=setup();s.character.data.mp=1;assert.equal(s.r.request(1),false);assert.equal(s.r.lastMessage,'MP insuficiente');s.character.restoreMP();s.combat.currentTarget=null;assert.equal(s.r.request(1),false);assert.equal(s.r.metrics.started,0);});
test('skill approach uses its own range and does not charge before arriving',()=>{const s=setup('bow',10);s.r.request(3);run(s,.1);assert.equal(s.character.data.mp,80);assert.equal(s.combat.state,'skillApproach');run(s,1.2);assert.equal(s.r.metrics.started,1);assert.ok(s.combat.distance(s.enemy)>5);assert.equal(s.character.data.mp,68);});
test('impossible route cancels without cost or cooldown',()=>{const s=setup('sword',4);s.world.obstacles.push({shape:'rect',x:2,z:0,halfX:.3,halfZ:20});s.r.request(1);run(s,.1);assert.equal(s.r.pending,null);assert.equal(s.character.data.mp,80);assert.equal(s.r.remaining('powerStrike'),0);assert.match(s.r.lastMessage,/caminho/);});
test('latest valid intent replaces the only pending action',()=>{const s=setup();s.r.request(1);s.r.request(5);assert.equal(s.r.pending.ability.id,'regeneration');run(s,.1);assert.equal(s.r.metrics.started,1);assert.equal(s.r.active.ability.id,'regeneration');assert.equal(s.r.remaining('powerStrike'),0);});
test('input buffer accepts last 0.3s of cooldown and waits to charge',()=>{const s=setup();s.r.cooldowns.set('powerStrike',.2);assert.equal(s.r.request(1),true);run(s,.1);assert.equal(s.character.data.mp,80);run(s,.2);assert.equal(s.r.metrics.started,1);assert.equal(s.character.data.mp,72);const t=setup();t.r.cooldowns.set('powerStrike',.4);assert.equal(t.r.request(1),false);});
test('active execution queues one later skill and completes before it starts',()=>{const s=setup();s.r.request(1);run(s,.1);s.r.request(5);run(s,.3);assert.equal(s.r.active.ability.id,'powerStrike');assert.equal(s.r.pending.ability.id,'regeneration');run(s,.5);assert.equal(s.r.active.ability.id,'regeneration');assert.equal(s.r.metrics.started,2);});
test('Power Strike is a single stronger physical hit with no stun',()=>{const s=setup();s.r.request(1);run(s,.4);assert.equal(s.r.metrics.impacts,1);assert.equal(s.enemy.hp,85);assert.notEqual(s.enemy.state,'stunned');});
test('Double Attack resolves hit, miss and critical independently',()=>{const s=setup('dagger');let rolls=[.1,.9,.5,.1,.01,.5];s.combat.random=()=>rolls.shift()??.99;s.r.request(2);run(s,.4);const hits=s.combat.events.filter(e=>e.ability==='doubleAttack');assert.equal(hits.length,2);assert.equal(hits[0].critical,false);assert.equal(hits[1].critical,true);const t=setup('dagger');let missRolls=[.1,.9,.5,.99];t.combat.random=()=>missRolls.shift()??.99;t.r.request(2);run(t,.4);assert.deepEqual(t.combat.events.filter(e=>e.ability==='doubleAttack').map(e=>e.hit),[true,false]);});
test('death on first multi-hit prevents corpse damage or retargeting',()=>{const s=setup('dagger');s.enemy.hp=1;const other=new Enemy({...s.enemy,id:'other'});s.combat.enemies.push(other);s.r.request(2);run(s,1);assert.equal(s.r.metrics.impacts,1);assert.equal(s.enemy.hp,0);assert.equal(other.hp,120);assert.equal(s.combat.currentTarget,null);});
test('Double Shot launches two projectiles with separate impacts',()=>{const s=setup('bow',5);s.r.request(3);run(s,.5);assert.equal(s.r.metrics.launched,2);assert.equal(s.r.projectiles.items.length,2);assert.equal(s.r.metrics.impacts,0);run(s,.6);assert.equal(s.r.metrics.impacts,2);assert.equal(s.r.projectiles.items.filter(p=>p.ability==='doubleShot').length,0);});
test('second projectile disappears when the first kills its target',()=>{const s=setup('bow',5);s.enemy.hp=1;s.r.request(3);run(s,1.2);assert.equal(s.r.metrics.launched,2);assert.equal(s.r.metrics.impacts,1);assert.equal(s.r.projectiles.items.length,0);});
test('Energy Ball has cast time and scales Magic Attack against Magic Defense',()=>{const s=setup('staff',5);s.enemy.stats.magicDefense=10;s.enemy.stats.physicalDefense=999;s.r.request(4);run(s,.6);assert.equal(s.r.metrics.launched,0);assert.equal(s.combat.state,'casting');run(s,1);assert.equal(s.r.metrics.launched,1);assert.equal(s.r.metrics.impacts,1);assert.equal(s.combat.events.find(e=>e.ability==='energyBall').damage,19);const t=setup('staff',5);t.character.data.attributes.int+=10;t.character.recalculate();t.enemy.stats.magicDefense=10;t.r.request(4);run(t,1.6);assert.ok(t.enemy.hp<s.enemy.hp);});
test('Regeneration is six periodic ticks, no instant heal, and expires',()=>{const s=setup();s.character.damage(80);s.r.request(5);run(s,.4);assert.equal(s.character.data.hp,80);assert.equal(s.r.periodic.items.length,1);run(s,6.2);assert.equal(s.r.metrics.ticks,6);assert.equal(s.r.periodic.items.length,0);assert.ok(Math.abs(s.character.data.hp-(80+6*8.325))<1e-8);});
test('generic periodic scheduler supports refresh and clamps to a fixed tick count',()=>{const effects=new PeriodicEffects();effects.apply({key:'x',interval:1,duration:3,value:2});let total=0;effects.update(.9,()=>true,e=>total+=e.value);assert.equal(total,0);effects.apply({key:'x',interval:1,duration:3,value:3});effects.update(10,()=>true,e=>total+=e.value);assert.equal(total,9);assert.equal(effects.items.length,0);});
test('pause freezes cast, cooldown, projectiles and periodic timers',()=>{const s=setup('bow',5);s.r.request(3);run(s,.4);s.r.periodic.apply({key:'test',target:s.character.data.id,interval:1,duration:3,effectType:'heal',value:1});s.game.paused=true;const before=JSON.stringify({time:s.r.time,active:s.r.active,p:s.r.projectiles.items,hot:s.r.periodic.items,cd:[...s.r.cooldowns]});run(s,5);assert.equal(JSON.stringify({time:s.r.time,active:s.r.active,p:s.r.projectiles.items,hot:s.r.periodic.items,cd:[...s.r.cooldowns]}),before);});
test('death cancels cast, queue, projectiles and periodic effects without reviving',()=>{const s=setup('bow',5);s.r.request(3);run(s,.5);s.r.request(5);s.r.periodic.apply({key:'test',target:s.character.data.id,interval:.1,duration:1,effectType:'heal',value:100});s.character.damage(999);run(s,.3);assert.equal(s.character.data.hp,0);assert.equal(s.r.active,null);assert.equal(s.r.pending,null);assert.equal(s.r.projectiles.items.length,0);assert.equal(s.r.periodic.items.length,0);});
test('manual movement interrupts cast and retains committed cost/cooldown',()=>{const s=setup('staff',5);s.r.request(4);run(s,.2);run(s,.1,120,{x:1,z:0});assert.equal(s.r.active,null);assert.equal(s.r.metrics.launched,0);assert.equal(s.character.data.mp,66);assert.ok(s.r.remaining('energyBall')>4);});
test('weapon changes reject pending and active execution without modifying equipment or cost',()=>{const s=setup('sword',10);s.r.request(1);run(s,.1);assert.equal(s.r.changeWeapon('bow'),false);assert.equal(s.r.pending.ability.id,'powerStrike');assert.equal(s.character.data.mp,80);s.combat.cancel();s.enemy.x=1.2;s.r.request(1);run(s,.1);assert.equal(s.r.changeWeapon('staff'),false);assert.equal(s.r.weapon,'sword');});
test('weapon changes in Idle work and auto-attack cannot bypass combat equipment lock',()=>{const s=setup();assert.equal(s.r.changeWeapon('dagger'),true);s.combat.select(s.enemy.id);run(s,.1);const before=JSON.stringify(s.combat.playerCycle);assert.equal(s.r.changeWeapon('bow'),false);assert.equal(JSON.stringify(s.combat.playerCycle),before);assert.equal(s.r.weapon,'dagger');assert.equal(s.character.data.classId,'novice');});
test('auto-attack completes its current impact, then skill executes and auto resumes',()=>{const s=setup();s.enemy.hp=1000;s.combat.select(s.enemy.id);run(s,.1);s.r.request(1);run(s,.3);assert.equal(s.r.metrics.started,0);assert.equal(s.combat.events.filter(e=>e.source==='player'&&!e.ability).length,1);run(s,1.6);assert.equal(s.r.metrics.impacts,1);assert.ok(s.combat.events.filter(e=>e.source==='player'&&!e.ability).length>=2);assert.equal(s.combat.state,'attacking');});
test('projectile path checks solids and lifetime; new target generation cannot receive old shots',()=>{const p=new Projectiles();p.launch({x:0,z:0,target:{id:'x'},speed:1,lifetime:1});let hits=0;p.update(2,()=>({x:5,z:0}),()=>true,()=>hits++);assert.equal(hits,0);assert.equal(p.items.length,0);const s=setup('bow',5);s.r.request(3);run(s,.5);s.world.obstacles.push({shape:'rect',x:4,z:0,halfX:.2,halfZ:20});run(s,.7);assert.equal(s.r.metrics.impacts,0);const t=setup('bow',5);t.r.request(3);run(t,.5);t.enemy.generation=1;run(t,.7);assert.equal(t.r.metrics.impacts,0);});
test('skill logical facing is independent from camera yaw',()=>{for(const yaw of [0,45,90,137,180,243,318]){const s=setup('staff',5);s.r.request(4);for(let i=0;i<30;i++)s.combat.update(1/60,{x:0,z:0},yaw*Math.PI/180);assert.equal(s.game.player.heading,Math.PI/2);}});
test('ability impacts and periodic counts agree at different FPS',()=>{for(const [weapon,slot] of [['dagger',2],['bow',3],['staff',4],['sword',5]]){const results=[];for(const fps of [30,60,144]){const s=setup(weapon,slot===2?1.2:5);s.character.damage(80);s.r.request(slot);run(s,7,fps);results.push([s.r.metrics.impacts,s.r.metrics.launched,s.r.metrics.ticks,s.character.data.mp]);}assert.deepEqual(results[0],results[1]);assert.deepEqual(results[1],results[2]);}});
test('weapon and known techniques survive save, old saves gain defaults without changing class',()=>{const s=setup('staff');s.character.data.knownAbilities=['energyBall','regeneration'];const data=decodeSave(encodeSave(s.character.snapshot(),1));assert.equal(data.equippedWeaponType,'staff');assert.deepEqual(data.knownAbilities,s.character.data.knownAbilities);assert.equal(decodeSave({level:1}).equippedWeaponType,null);assert.equal(data.classId,'novice');assert.throws(()=>decodeSave({equippedWeaponType:'unknown'}));});

test('queued skills revalidate MP and expiration before execution',()=>{const s=setup();s.r.request(1);s.character.data.mp=0;run(s,.1);assert.equal(s.r.metrics.started,0);assert.equal(s.r.pending,null);assert.equal(s.r.remaining('powerStrike'),0);const t=setup('sword',12);t.r.request(1);t.r.pending.expires=.01;run(t,.1);assert.equal(t.r.pending,null);assert.equal(t.character.data.mp,80);assert.match(t.r.lastMessage,/expirada/);});
test('melee impact revalidates LOS after cast has committed its cost',()=>{const s=setup();s.r.request(1);run(s,.1);s.world.obstacles.push({shape:'rect',x:.6,z:0,halfX:.1,halfZ:1});run(s,.3);assert.equal(s.r.metrics.impacts,0);assert.equal(s.character.data.mp,72);});
test('returning target invalidates queued skill without consuming MP',()=>{const s=setup('sword',10);s.r.request(1);run(s,.1);s.enemy.state='returning';run(s,.1);assert.equal(s.r.pending,null);assert.equal(s.character.data.mp,80);assert.equal(s.r.remaining('powerStrike'),0);});

import {EnemyAI} from '../src/simulation/enemy-ai.js';
import {createEnemies} from '../src/domain/enemies/spawns.js';
test('ranged skill damage triggers the existing AI and remains stable with twenty enemies',()=>{const s=setup('staff',6);s.combat.enemies=createEnemies(Array.from({length:20},(_,i)=>({id:'ability-scale-'+i,enemyType:'trainingSlime',position:{x:Math.cos(i*Math.PI/10)*6,z:Math.sin(i*Math.PI/10)*6},overrides:{detectionRange:1.5}})),s.world);s.enemy=s.combat.enemies[0];s.combat.currentTarget=s.enemy.id;s.combat.retaliation=true;s.combat.ai=new EnemyAI(s.combat);s.character.modifiers.other={stats:{maxHP:100000}};s.character.recalculate();s.character.restoreHP();s.r.request(4);run(s,1.8);assert.equal(s.r.metrics.impacts,1);assert.equal(s.enemy.aggroReason,'damage');const start=performance.now();run(s,10);console.log('Abilities + 20 enemies / 10 simulated seconds:',(performance.now()-start).toFixed(1),'ms; impacts:',s.r.metrics.impacts);assert.ok(s.combat.enemies.every(e=>Number.isFinite(e.x+e.z+e.hp)));});
