import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Character,createCharacter} from '../src/domain/character/character.js';
import {BALANCE} from '../src/domain/character/balance.js';
import {Inventory,ITEMS,equipmentBlocked} from '../src/domain/items/inventory.js';
import {learnAbility,NOVICE_TREE,nodeState} from '../src/domain/abilities/skill-tree.js';
import {decodeSave,encodeSave,CharacterSave} from '../src/adapters/persistence/character-save.js';
import {AreaSession,createAreas} from '../src/simulation/areas.js';
import {generateFloor} from '../src/world/tower.js';
import {generateEncounter} from '../src/domain/enemies/encounters.js';
import {createEnemies} from '../src/domain/enemies/spawns.js';
import {EnemyAI} from '../src/simulation/enemy-ai.js';
import {canStand,clearSegment} from '../src/world/collision.js';
import {LOOT_POOL,chestReward} from '../src/domain/items/loot.js';
const hub=JSON.parse(fs.readFileSync(new URL('../src/data/hub.json',import.meta.url)));
const make=(weapon='trainingBow',type='trainingSlime')=>{
  const s=new AreaSession(createAreas(hub),new Character(),{seed:42}),c=s.combat.character,bag=new Inventory(c);bag.acquire(weapon);bag.equip(0);s.startRun();
  const world=s.game.world;world.obstacles=[];s.combat.enemies=createEnemies([{id:'target',enemyType:type,position:{x:0,z:0},overrides:{aggressive:false,ambient:true,noRespawn:true,stats:{maxHP:1000}}}],world);s.combat.ai=new EnemyAI(s.combat);s.combat.random=()=>.5;Object.assign(s.game.player,{x:0,z:5});return s;
};
const run=(s,seconds,fps=30)=>{for(let i=0;i<Math.round(seconds*fps);i++)s.update(1/fps,{x:0,z:0},0);};

test('iteration 08 reset includes every persistent progression field exactly once',()=>{for(const version of [undefined,2,3]){const c=new Character();Object.assign(c.data,{progressionVersion:version,level:5,xp:100,gold:800,skillSpaces:4,attributePoints:20,knownAbilities:['regeneration']});c.data.attributes.str=30;c.data.firstSteps.entered=true;new Inventory(c).acquire('expeditionChest',{rewardSeed:12});const reset=decodeSave(encodeSave(c.snapshot(),1));assert.deepEqual(reset,createCharacter());const next=new Character(reset);next.gainXP(100);learnAbility(next,'regeneration');assert.deepEqual(decodeSave(encodeSave(next.snapshot(),2)),next.snapshot());assert.equal(next.data.level,2);}});
test('current save rejects invalid skill balances and future progressions',()=>{for(const value of [-1,.5,Infinity,BALANCE.maxPoints+1]){const c=new Character();c.data.skillSpaces=value;assert.throws(()=>decodeSave(encodeSave(c.snapshot(),1)));}const c=new Character();c.data.progressionVersion=5;assert.throws(()=>decodeSave(encodeSave(c.snapshot(),1)));});
test('new novice has no free techniques; level thresholds grant independent resources',()=>{const c=new Character();for(const node of NOVICE_TREE){assert.equal(nodeState(c,node),'unlearned');assert.throws(()=>learnAbility(c,node.id),/Espaço/);}c.gainXP(450);assert.equal(c.data.level,3);assert.equal(c.data.attributePoints,10);assert.equal(c.data.skillSpaces,2);learnAbility(c,'energyBall');assert.equal(c.data.skillSpaces,1);assert.equal(learnAbility(c,'energyBall'),false);assert.equal(c.data.skillSpaces,1);learnAbility(c,'regeneration');assert.equal(c.data.skillSpaces,0);assert.throws(()=>learnAbility(c,'powerStrike'));assert.deepEqual(decodeSave(encodeSave(c.snapshot(),1)),c.snapshot());});
test('five styles are independent and purchased with exactly five earned spaces',()=>{const c=new Character();c.gainXP(3000);assert.equal(c.data.skillSpaces,5);for(const n of [...NOVICE_TREE].reverse())learnAbility(c,n.id);assert.equal(c.data.skillSpaces,0);assert.equal(c.data.knownAbilities.length,5);assert.equal(c.data.classId,'novice');});
for(const weapon of ['trainingBow','trainingStaff']){
  test(weapon+' launches before damage, resolves the correct defense and shares projectile infrastructure',()=>{const s=make(weapon),c=s.combat,e=c.enemies[0];e.ambient=false;c.retaliation=false;c.ai=null;e.stats.physicalDefense=weapon==='trainingStaff'?999:0;e.stats.magicDefense=weapon==='trainingBow'?999:0;c.select(e.id);run(s,.3);assert.equal(c.projectiles,c.abilities.projectiles);assert.ok(c.projectiles.items.length);assert.equal(e.hp,1000);assert.ok(equipmentBlocked(c));run(s,.7);assert.ok(e.hp<1000);assert.equal(c.events.find(x=>x.source==='player').damageType,weapon==='trainingBow'?'physical':'magic');});
  test(weapon+' projectiles freeze on pause and cancel on death, generation change or area transition',()=>{for(const mode of ['death','generation','area','playerDeath']){const s=make(weapon),c=s.combat,e=c.enemies[0];e.ambient=false;c.select(e.id);run(s,.3);assert.ok(c.projectiles.items.length);s.game.paused=true;const before=JSON.stringify(c.projectiles.items);run(s,2);assert.equal(JSON.stringify(c.projectiles.items),before);s.game.paused=false;if(mode==='death')e.damage(9999);if(mode==='generation')e.generation++;if(mode==='area')s.enter(s.hubId);if(mode==='playerDeath')c.character.damage(9999);c.cancel(true);run(s,.1);assert.equal(c.projectiles.items.length,0);assert.equal(c.events.filter(e=>e.source==='player').length,0);}});
  test(weapon+' projectile is blocked by cover added after launch',()=>{const s=make(weapon),c=s.combat,e=c.enemies[0];e.ambient=false;c.select(e.id);run(s,.3);c.cancel();s.game.world.obstacles.push({id:'cover',shape:'rect',x:0,z:2.5,halfX:3,halfZ:.3});run(s,1);assert.equal(e.hp,1000);assert.equal(e.targetId,null);assert.equal(c.projectiles.items.length,0);});
  test(weapon+' basic impacts are stable at 30, 60 and 144 FPS',()=>{const damages=[30,60,144].map(fps=>{const s=make(weapon),e=s.combat.enemies[0];e.ambient=false;s.combat.retaliation=false;s.combat.ai=null;s.combat.select(e.id);run(s,5,fps);return 1000-e.hp;});assert.equal(new Set(damages).size,1);});
}
test('sword hits harder while dagger cycles visibly faster at shorter reach',()=>{const results={};for(const weapon of ['trainingSword','trainingDagger']){const s=make(weapon),e=s.combat.enemies[0];e.ambient=false;s.combat.retaliation=false;Object.assign(s.game.player,{x:0,z:1.2});s.combat.select(e.id);run(s,5);const hits=s.combat.events.filter(e=>e.source==='player');results[weapon]={hits:hits.length,damage:hits[0].damage};assert.equal(ITEMS[weapon].basicAttack.delivery,'melee');}assert.ok(results.trainingSword.damage>results.trainingDagger.damage);assert.ok(results.trainingDagger.hits>results.trainingSword.hits);assert.ok(ITEMS.trainingDagger.basicAttack.attackRange<ITEMS.trainingSword.basicAttack.attackRange);});
for(const type of ['trainingSlime','jumpingSlime','magicSlime']){
  test(type+' wanders passively, responds to impact, returns and never respawns',()=>{const s=make('trainingBow',type),e=s.combat.enemies[0];Object.assign(s.game.player,{x:0,z:1});const positions=new Set();for(let i=0;i<600;i++){run(s,1/30);positions.add(e.x.toFixed(2)+','+e.z.toFixed(2));assert.equal(e.targetId,null);}assert.ok(positions.size>5);s.combat.select(e.id);run(s,1);assert.equal(e.targetId,s.combat.character.data.id);s.combat.cancel(true);s.combat.ai.returning(e,'test-leash');Object.assign(s.game.player,{x:10,z:10});run(s,15);assert.equal(e.targetId,null);assert.equal(e.state,'idle');e.damage(9999);run(s,40);assert.equal(e.state,'removed');assert.equal(e.generation,0);assert.equal(e.respawnTime,undefined);});
}
test('mobile approach follows navigation without crossing walls',()=>{const s=make('trainingSword','jumpingSlime'),e=s.combat.enemies[0];e.ambient=false;s.game.world.obstacles.push({id:'wall',shape:'rect',x:0,z:2.5,halfX:2,halfZ:.5});s.combat.ai.onDamaged(e,s.combat.character.data.id);for(let i=0;i<180;i++){const old={x:e.x,z:e.z};run(s,1/30);assert.ok(canStand(s.area,e.x,e.z,e.radius));assert.ok(clearSegment(s.area,old,e,e.radius));}assert.ok(e.z>2.5);});
test('ranged enemy retreats, launches magic, and cover prevents damage',()=>{const s=make('trainingSword','magicSlime'),c=s.combat,e=c.enemies[0];e.ambient=false;Object.assign(s.game.player,{x:0,z:1.5});c.ai.onDamaged(e,c.character.data.id);run(s,1.5);assert.ok(c.distance(e)>2.8);const hp=c.character.data.hp;run(s,2);assert.ok(c.character.data.hp<hp);assert.ok(c.events.some(e=>e.source==='enemy'&&e.damageType==='magic'));c.projectiles.clear();c.enemyCycles.clear();Object.assign(e,{x:0,z:0});Object.assign(s.game.player,{x:0,z:5});s.area.obstacles.push({id:'wall',shape:'rect',x:0,z:2.5,halfX:11,halfZ:.4});const before=c.character.data.hp;run(s,1);assert.equal(c.character.data.hp,before);});
test('100 seeds meet encounter constraints with independent reproducible composition and reachable spawns',()=>{const variants=new Set();for(let seed=0;seed<100;seed++)for(const floor of [1,2,3]){const w=generateFloor(seed,floor,hub.id),types=w.encounter.map(e=>e.enemyType);assert.deepEqual(w.encounter,generateEncounter(seed,floor,types.length));if(floor===1)assert.ok(types.every(t=>t==='trainingSlime'));if(floor>=2)assert.ok(types.includes('jumpingSlime'));if(floor===3){assert.ok(types.includes('magicSlime'));variants.add(types.join(','));}for(const spawn of w.enemySpawns)assert.ok(canStand(w,spawn.position.x,spawn.position.z,.85));}assert.ok(variants.size>5);});
for(const id of ['apprenticeHood','lightVest','agileBoots','strengthRing'])test(id+' trades stats within its slot and recalculates through swap and reload',()=>{const c=new Character(),bag=new Inventory(c),base={...c.stats},def=ITEMS[id],old=Object.values(ITEMS).find(i=>i.equipSlot===def.equipSlot&&i.id!==id);bag.acquire(old.id);bag.equip(0,def.equipSlot);bag.acquire(id);const index=c.data.inventory.slots.findIndex(i=>i?.definitionId===id);bag.equip(index,def.equipSlot);for(const [key,v] of Object.entries(def.stats))assert.equal(c.stats[key],base[key]+v);c.recalculate();assert.deepEqual(new Character(decodeSave(encodeSave(c.snapshot(),1))).stats,c.stats);bag.unequip(def.equipSlot);assert.deepEqual(c.stats,base);assert.ok(LOOT_POOL.includes(id));});
test('expanded pool has deterministic weighted rewards and eight choices',()=>{assert.equal(LOOT_POOL.length,8);for(let i=0;i<50;i++){const item={definitionId:'expeditionChest',rewardSeed:i};assert.deepEqual(chestReward(item),chestReward(item));}});

test('opening an old browser profile persists the reset before returning and never repeats it',async()=>{let raw=encodeSave({...createCharacter(),progressionVersion:3,level:5,gold:100},7),writes=0;const previous=globalThis.indexedDB;globalThis.indexedDB={open(){const request={};queueMicrotask(()=>{request.result={close(){},transaction(){return {objectStore(){return {get(){const read={};queueMicrotask(()=>{read.result=structuredClone(raw);read.onsuccess();});return read;}};}};}};request.onsuccess();});return request;}};class Profile extends CharacterSave{async save(data){writes++;assert.equal(this.revision,raw.revision);raw=encodeSave(data,++this.revision);}}try{const first=await new Profile().open();assert.deepEqual(first,createCharacter());assert.equal(writes,1);const c=new Character(first);c.gainXP(100);learnAbility(c,'powerStrike');raw=encodeSave(c.snapshot(),9);const restored=await new Profile().open();assert.equal(writes,1);assert.deepEqual(restored,c.snapshot());}finally{globalThis.indexedDB=previous;}});
