import {ABILITIES,WEAPONS} from '../domain/abilities/definitions.js';
export class AbilityHud {
  constructor(runtime,{isBlocked,debug,save}){this.runtime=runtime;this.isBlocked=isBlocked;this.abort=new AbortController();this.root=document.createElement('section');this.root.id='ability-bar';this.root.setAttribute('aria-label','Habilidades do Novato');
    this.root.innerHTML='<div id="ability-status" role="status"></div><div class="ability-slots">'+runtime.hotbar.map((id,i)=>{const a=ABILITIES[id];return `<button class="ability-slot" data-slot="${i+1}" ${a?'':'disabled'} aria-label="${i+1} — ${a?.name??'Slot vazio'}"><kbd>${i+1}</kbd><span class="ability-icon">${a?.icon??'·'}</span><span class="ability-name">${a?.name??'Vazio'}</span><span class="ability-cooldown"></span></button>`;}).join('')+'</div>';
    document.querySelector('#app').append(this.root);
    this.root.addEventListener('click',event=>{const b=event.target.closest('[data-slot]');if(b&&!isBlocked())runtime.request(Number(b.dataset.slot));});
    window.addEventListener('keydown',event=>{if(event.repeat||isBlocked()||event.target.isContentEditable||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.ctrlKey||event.altKey||event.metaKey)return;if(/^[1-8]$/.test(event.key)){event.preventDefault();runtime.request(Number(event.key));}}, {signal:this.abort.signal});
    this.weaponTools=document.createElement('div');this.weaponTools.id='ability-debug';this.weaponTools.hidden=!debug;this.weaponTools.innerHTML='<label>Arma provisória <select id="debug-weapon">'+Object.entries(WEAPONS).map(([id,w])=>`<option value="${id}">${w.name}</option>`).join('')+'</select></label><pre id="ability-debug-values"></pre>';document.querySelector('#combat-debug').append(this.weaponTools);
    this.weaponTools.querySelector('select').addEventListener('change',async event=>{const before=runtime.weapon,snapshot=runtime.character.snapshot();if(!runtime.changeWeapon(event.target.value)){event.target.value=before;return;}this.saving=true;try{await save();}catch(error){runtime.character.data=snapshot;runtime.character.recalculate();runtime.feedback(error.message);}finally{this.saving=false;this.update();}});
    this.update();
  }
  update(){const r=this.runtime,blocked=this.isBlocked();for(const button of this.root.querySelectorAll('[data-slot]')){const id=r.hotbar[Number(button.dataset.slot)-1],a=ABILITIES[id];if(!a)continue;const reason=r.reason(a,r.targetRef()),remaining=r.remaining(id),weapon=a.weaponRequirements.length?'Requer '+a.weaponRequirements.map(w=>WEAPONS[w].name).join(' / '):'Sem requisito de arma';button.title=`${a.name}\n${a.description}\n${weapon}\nMP: ${a.manaCost} · Recarga: ${a.cooldown}s${a.requiresTarget?' · Alcance: '+a.range:''}${reason?'\n'+reason:''}`;button.setAttribute('aria-disabled',String(blocked||!!reason));button.classList.toggle('unavailable',!!reason);button.classList.toggle('queued',r.pending?.ability.id===id);button.classList.toggle('executing',r.active?.ability.id===id);button.querySelector('.ability-cooldown').textContent=remaining>0?remaining.toFixed(1)+'s':'';}
    const active=r.active,pending=r.pending,hot=r.periodic.items[0];let status='';if(active){const elapsed=r.time-active.started;status=(elapsed<active.ability.castTime?'Conjurando ':elapsed<active.lastImpact?'Executando ':'Recuperando · ')+active.ability.name;}if(pending)status+=(status?' · A seguir: ':'Preparando: ')+pending.ability.name;if(hot)status+=(status?' · ':'')+'Regeneração '+Math.max(0,hot.duration-hot.elapsed).toFixed(1)+'s';this.root.querySelector('#ability-status').textContent=status;
    const select=this.weaponTools.querySelector('select');select.value=r.weapon;select.disabled=!!this.saving;this.weaponTools.querySelector('#ability-debug-values').textContent=`Área: ${r.combat.game.areaId??r.combat.game.world.id} · Andar: ${r.combat.game.floorId??'—'}\nInventário: ${r.character.data.inventory.slots.filter(Boolean).length}/${r.character.data.inventory.capacity} · Aprendidas: ${r.character.data.knownAbilities.length}\nCooldowns: ${[...r.cooldowns.keys()].filter(id=>r.remaining(id)>0).map(id=>id+': '+r.remaining(id).toFixed(1)).join(', ')||'—'}\nArma: ${WEAPONS[r.weapon]?.name??'Sem arma'}\nFila: ${pending?.ability.id??'—'} | Execução: ${active?.ability.id??'—'}\nProjéteis: ${r.projectiles.items.length} | Efeitos: ${r.periodic.items.length}\nInícios ${r.metrics.started} · impactos ${r.metrics.impacts} · lançamentos ${r.metrics.launched} · ticks ${r.metrics.ticks}\n${r.lastMessage}`;
  }
  dispose(){this.abort.abort();this.root.remove();this.weaponTools.remove();}
}
