import {COMBAT} from '../domain/combat/config.js';
import {hitChance} from '../domain/combat/attack.js';
export class CombatHud {
  constructor(combat,view,debug){this.combat=combat;this.view=view;this.nodes=new Map();this.enemyLabels=new Map();this.frameStart=performance.now();this.frameCount=0;this.fps=0;this.nextDebug=0;
    this.root=document.createElement('div');this.root.id='combat-ui';this.root.innerHTML='<section id="target-panel" class="panel" hidden><strong id="target-name"></strong><label id="target-hp-label"></label><progress id="target-hp" aria-labelledby="target-name target-hp-label"></progress><small id="combat-state"></small></section><div id="combat-numbers" aria-hidden="true"></div><div id="death-notice" role="status" hidden>Você caiu. Retornando ao Refúgio…</div><div id="enemy-label">Slime de Treino · Nv. 1<small>Clique para treinar combate</small></div><details id="combat-debug" class="panel" hidden><summary>Depuração do combate</summary><label><input id="enemy-retaliation" type="checkbox" checked> IA e ataques ativos</label><pre id="combat-debug-values"></pre><label><input id="ai-ranges" type="checkbox"> Mostrar visão, alcance, leash e rotas</label><pre id="ai-debug-values"></pre></details>';
    document.querySelector('#app').append(this.root);this.root.querySelector('#combat-debug').hidden=!debug;
    this.root.querySelector('#ai-ranges').onchange=event=>{if(combat.ai)combat.ai.debug=event.target.checked;};
    this.root.querySelector('#enemy-label').hidden=true;
    combat.enemies.forEach((enemy,index)=>{const label=index===0?this.root.querySelector('#enemy-label'):document.createElement('div');label.className='enemy-label';label.dataset.enemyId=enemy.id;if(index>0)this.root.append(label);this.enemyLabels.set(enemy.id,label);});
    this.root.querySelector('#enemy-retaliation').onchange=event=>{combat.retaliation=event.target.checked;};
  }
  update(){const c=this.combat,v=this.view,t=c.target,$=id=>this.root.querySelector('#'+id);
    $('target-panel').hidden=!t||!!t.boss;if(t){$('target-name').textContent=`${t.name} · Nv. ${t.level}`;$('target-hp-label').textContent=`HP ${t.hp} / ${t.stats.maxHP}`;$('target-hp').max=t.stats.maxHP;$('target-hp').value=t.hp;$('combat-state').textContent={chasing:'Aproximando…',attacking:'Ataque automático',idle:'Alvo selecionado',moving:'Reposicionando',dead:'Derrotado',casting:'Conjurando',usingSkill:'Usando habilidade',recovering:'Recuperando',skillApproach:'Aproximando para habilidade'}[c.state]??c.state;}
    $('death-notice').hidden=c.state!=='dead';for(const enemy of c.enemies){const point=v.screenPoint(enemy.x,1.25,enemy.z),label=this.enemyLabels.get(enemy.id);label.hidden=enemy.dormant||!enemy.alive||!point.visible;label.style.left=point.x+'px';label.style.top=point.y+'px';label.textContent=c.ai?.debug?enemy.id+' · '+enemy.state:enemy.boss?'Slime Guardião':enemy.name+(enemy.state==='returning'?' · Retornando':enemy.ambient&&enemy.state==='idle'?' · Passivo':' · Nv. '+enemy.level);}
    this.frameCount++;const now=performance.now();if(now-this.frameStart>=1000){this.fps=this.frameCount*1000/(now-this.frameStart);this.frameStart=now;this.frameCount=0;}
    if(!c.ai&&!$('combat-debug').hidden)$('ai-debug-values').textContent='Hub seguro · 0 inimigos · IA desativada';
    if(c.ai&&!$('combat-debug').hidden&&now>=this.nextDebug){this.nextDebug=now+250;$('ai-debug-values').textContent=`FPS observado: ${this.fps.toFixed(0)} | Inimigos: ${c.enemies.length}\nRotas calculadas: ${c.ai.metrics.paths} | Fallbacks: ${c.ai.metrics.fallbacks}\n`+c.enemies.map(e=>`${e.id}: ${e.state} | alvo ${e.targetId??'—'} | dist ${c.distance(e).toFixed(1)} | respawn ${e.noRespawn?'não reaparece':e.alive?'—':Math.max(0,e.respawnTime-e.deathTime).toFixed(1)+'s'}\n origem (${e.spawnPosition.x}, ${e.spawnPosition.z}) · motivo ${e.aggroReason??'—'}`).join('\n');}
    for(const event of c.events){const age=c.game.elapsed-event.time;if(age>1.4)continue;let node=this.nodes.get(event);if(!node){node=document.createElement('span');node.textContent=event.text;node.className=event.heal?'combat-result heal':event.death?'combat-result death':event.critical?'combat-result critical':event.source==='enemy'?'combat-result incoming':'combat-result';$('combat-numbers').append(node);this.nodes.set(event,node);}const p=v.screenPoint(event.x,1.6+age*.7,event.z);node.hidden=!p.visible;node.style.left=p.x+'px';node.style.top=p.y+'px';node.style.opacity=String(Math.min(1,(1.4-age)*2));}
    for(const [event,node] of this.nodes)if(c.game.elapsed-event.time>1.4){node.remove();this.nodes.delete(event);}
    if(!$('combat-debug').hidden){const s=c.character.stats;$('combat-debug-values').textContent=`Player ATK ${s.physicalAttack.toFixed(1)} | ASPD ${s.attackSpeed.toFixed(3)}\nAccuracy ${s.accuracy}% | Crit ${s.criticalChance}%\nTarget HP ${t?.hp??'—'} | DEF ${t?.stats.physicalDefense??'—'} | EVA ${t?.stats.evasion??'—'}\nDistance ${t?c.distance(t).toFixed(2):'—'} | Range ${c.attackRange}\nState ${c.state} | Phase ${c.playerCycle.phase}\nNext impact ${(c.playerCycle.phase==='windup'?c.playerCycle.remaining:c.playerCycle.remaining+COMBAT.windupFraction/s.attackSpeed).toFixed(2)}s\nHit ${t?(hitChance(s,t.stats)*100).toFixed(1)+'%':'—'} | Last ${c.lastResult}`;}
  }
  dispose(){this.root.remove();}
}
