import {RewardReel} from './reward-reel.js';
import {LOOT_POOL} from '../domain/items/loot.js';
import {validateChest,grantChest} from '../domain/items/chest.js';
import {ITEMS} from '../domain/items/inventory.js';
export class RewardPanel {
  constructor(character,{open,save,safe,notify}){Object.assign(this,{character,openDialog:open,save,safe,notify});this.dialog=document.createElement('dialog');this.dialog.id='reward-dialog';this.dialog.className='rpg-dialog';this.dialog.setAttribute('aria-label','Recompensa do baú');this.dialog.innerHTML='<button class="close-button" data-close aria-label="Fechar recompensa">×</button><span class="eyebrow">RECOMPENSA DA EXPEDIÇÃO</span><h2>Abra seu baú</h2><div class="reel-window"><div class="reel-indicator">▼</div><div class="reel-track"></div></div><p class="reel-status" role="status">Pressione Espaço para desacelerar.</p><button class="primary-button" id="stop-reel">Desacelerar · Espaço</button>';document.querySelector('#app').append(this.dialog);this.dialog.addEventListener('cancel',e=>{if(this.busy)e.preventDefault();});this.dialog.querySelector('#stop-reel').onclick=()=>this.stop();this.key=e=>{if(this.dialog.open&&e.code==='Space'){e.preventDefault();if(!e.repeat)this.stop();}};window.addEventListener('keydown',this.key);}
  show(instanceId){this.selection=validateChest(this.character,instanceId,this.safe());const {reward}=this.selection;this.instanceId=instanceId;this.reel=new RewardReel(reward,LOOT_POOL);this.busy=true;this.committing=false;this.dialog.querySelector('[data-close]').disabled=true;this.dialog.querySelector('#stop-reel').disabled=false;this.dialog.querySelector('.reel-status').textContent='Pressione Espaço para desacelerar. Você receberá um equipamento e ouro.';this.track=this.dialog.querySelector('.reel-track');this.renderCards();this.openDialog('reward-dialog');this.notify('Baú aberto · pressione Espaço');let previous=performance.now();const frame=now=>{if(!this.dialog.open)return;this.reel.update(Math.max(0,Math.min(.25,(now-previous)/1000)));previous=now;this.track.style.transform=`translateX(calc(50% - ${this.reel.offset*112+56}px))`;if(this.reel.phase==='stopped'){this.commit();return;}this.frame=requestAnimationFrame(frame);};this.frame=requestAnimationFrame(frame);}
  renderCards(){this.track.innerHTML=this.reel.cards.map(id=>`<div class="reel-item"><span>${ITEMS[id].icon}</span><small>${ITEMS[id].name}</small></div>`).join('');}
  stop(){if(!this.busy||this.reel.phase!=='spinning')return;this.reel.stop();this.renderCards();this.dialog.querySelector('#stop-reel').disabled=true;this.dialog.querySelector('.reel-status').textContent='Desacelerando…';}
  async commit(){if(this.committing)return;this.committing=true;const before=this.character.snapshot();try{const reward=grantChest(this.character,this.selection,this.safe());await this.save();this.dialog.querySelector('.reel-status').textContent=`ITEM OBTIDO: ${ITEMS[reward.itemId].name} · OURO: +${reward.gold}. Abra C para evoluir seus atributos.`;this.notify('Recompensa recebida · +'+reward.gold+' ouro');}catch(error){this.character.data=before;this.character.recalculate();this.dialog.querySelector('.reel-status').textContent=error.message+' O baú foi preservado. Feche e tente novamente.';}finally{this.busy=false;this.dialog.querySelector('[data-close]').disabled=false;}}
  dispose(){cancelAnimationFrame(this.frame);window.removeEventListener('keydown',this.key);this.dialog.remove();}
}
