import {BALANCE} from '../domain/character/balance.js';
import {Inventory,ITEMS,EQUIPMENT_SLOTS,equipmentBlocked} from '../domain/items/inventory.js';
import {ABILITIES,WEAPONS} from '../domain/abilities/definitions.js';
import {NOVICE_TREE,nodeState,learnAbility} from '../domain/abilities/skill-tree.js';
const slotNames={weapon:'Arma',head:'Cabeça',chest:'Peitoral',legs:'Calças',boots:'Botas',ring:'Anel',necklace:'Colar',talisman:'Talismã'};
const statNames={physicalAttack:'Ataque físico',magicAttack:'Ataque mágico',attackSpeed:'Velocidade de ataque',physicalDefense:'Defesa física',magicDefense:'Defesa mágica',maxHP:'HP máximo',maxMP:'MP máximo',evasion:'Esquiva'};
const itemInfo = item => Object.entries(item.stats).map(([key,value])=>`${statNames[key]??key} +${value}`).join(' · ');
export class RpgPanels {
  constructor(character,combat,{open,isBlocked,save,onEquipment,onChest}){
    this.onChest=onChest;this.character=character;this.combat=combat;this.inventory=new Inventory(character);this.openDialog=open;this.save=save;this.onEquipment=onEquipment;this.abort=new AbortController();this.selectedItem=null;this.selectedSkill=NOVICE_TREE[0].id;
    this.dialogs={};for(const [id,title] of [['inventory','Inventário e equipamentos'],['skills','Caminhos do Novato'],['shop','Armeiro do Refúgio']]){
      const dialog=document.createElement('dialog');dialog.id=id+'-dialog';dialog.className='rpg-dialog';dialog.setAttribute('aria-label',title);dialog.innerHTML=`<button class="close-button" aria-label="Fechar ${title}" data-close>×</button><span class="eyebrow">${id==='shop'?'ARMAS DE TREINO · 0 MOEDAS':'NOVATO · BETA 0.1.0'}</span><h2>${title}</h2><div class="rpg-content"></div><p class="rpg-feedback" role="status"></p>`;document.querySelector('#app').append(dialog);this.dialogs[id]=dialog;dialog.addEventListener('click',event=>this.click(id,event));
    }
    this.launcher=document.createElement('nav');this.launcher.id='rpg-menu';this.launcher.setAttribute('aria-label','Painéis do jogador');this.launcher.innerHTML='<button data-panel="inventory">Inventário <kbd>I</kbd></button><button data-panel="skills">Habilidades <kbd>TAB</kbd></button>';document.querySelector('.rpg-hud').append(this.launcher);
    this.launcher.onclick=event=>{const id=event.target.closest('[data-panel]')?.dataset.panel;if(id&&!isBlocked())this.show(id);};
    window.addEventListener('keydown',event=>{if(event.repeat||event.ctrlKey||event.altKey||event.metaKey)return;const key=event.key.toLowerCase(),id=key==='tab'?'skills':key==='i'?'inventory':null;if(!id||event.target.isContentEditable||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName))return;if(this.dialogs[id].open){event.preventDefault();if(!this.busy)this.dialogs[id].close();}else if(!isBlocked()){event.preventDefault();this.show(id);}}, {signal:this.abort.signal});
    // Saving mutations finish before the modal can resume gameplay.
    for(const dialog of Object.values(this.dialogs))dialog.addEventListener('cancel',event=>{if(this.busy)event.preventDefault();});
  }
  show(id){this.dialogs[id].querySelector('.rpg-feedback').textContent='';this.render(id);this.openDialog(id+'-dialog');}
  async mutate(id,action){if(this.busy)return;const snapshot=this.character.snapshot();this.busy=true;this.render(id);try{const message=action();this.render(id);await this.save();this.dialogs[id].querySelector('.rpg-feedback').textContent=message;}catch(error){this.character.data=snapshot;this.character.recalculate();this.onEquipment();this.dialogs[id].querySelector('.rpg-feedback').textContent=error.message;}finally{this.busy=false;this.render(id);}}
  click(id,event){const b=event.target.closest('button');if(!b||this.busy)return;
    if(b.dataset.item!==undefined){this.selectedItem=Number(b.dataset.item);this.render(id);}
    if(b.dataset.node){this.selectedSkill=b.dataset.node;this.render(id);}
    if(b.dataset.acquire)this.mutate(id,()=>{this.inventory.acquire(b.dataset.acquire);return 'Arma adicionada ao inventário. Abra I para equipar.';});
    if(b.dataset.learn)this.mutate(id,()=>{learnAbility(this.character,b.dataset.learn);return 'Habilidade aprendida e disponível na hotbar.';});
    if(b.dataset.openChest){try{this.onChest(b.dataset.openChest);}catch(error){this.dialogs[id].querySelector('.rpg-feedback').textContent=error.message;}return;}
    if(b.dataset.equip!==undefined)this.mutate(id,()=>{this.inventory.equip(Number(b.dataset.equip),ITEMS[this.character.data.inventory.slots[Number(b.dataset.equip)]?.definitionId]?.equipSlot,equipmentBlocked(this.combat));this.onEquipment();return 'Equipamento aplicado. Estatísticas recalculadas.';});
    if(b.dataset.unequip)this.mutate(id,()=>{this.inventory.unequip(b.dataset.unequip,equipmentBlocked(this.combat));this.onEquipment();return 'Equipamento devolvido ao inventário.';});
  }
  render(id){const root=this.dialogs[id].querySelector('.rpg-content'),d=this.character.data,busy=this.busy?'disabled':'',blocked=equipmentBlocked(this.combat);this.dialogs[id].querySelector('[data-close]').disabled=!!this.busy;
    if(id==='shop')root.innerHTML='<p>Experimente os quatro estilos. Uma cópia de cada arma por personagem. Adquirir não equipa a arma.</p><div class="shop-grid">'+Object.values(ITEMS).filter(i=>i.type==='weapon').map(item=>`<article class="item-card"><span class="item-symbol">${item.icon}</span><h3>${item.name}</h3><p>${item.description}</p><p>${itemInfo(item)}</p><small>0 moedas · Arma de treino</small><button data-acquire="${item.id}" ${busy|| (this.inventory.owns(item.id)?'disabled':'')}>${this.inventory.owns(item.id)?'Já possuído':'Adquirir gratuitamente'}</button></article>`).join('')+'</div>';
    if(id==='inventory'){
      const item=d.inventory.slots[this.selectedItem],definition=ITEMS[item?.definitionId];
      root.innerHTML=`<p>${d.inventory.slots.filter(Boolean).length} / ${d.inventory.capacity} slots ocupados · Selecione um item para ver os detalhes.</p>${blocked?'<p class="equipment-warning">Não é possível trocar equipamento durante combate.</p>':''}<div class="inventory-layout"><section><div class="inventory-grid">${d.inventory.slots.map((item,index)=>{const def=ITEMS[item?.definitionId];return `<button class="inventory-slot ${index===this.selectedItem?'selected':''}" data-item="${index}" ${busy} aria-label="Slot ${index+1}: ${def?.name??'Vazio'}" title="${def?def.name+' · '+itemInfo(def):'Slot vazio'}"><span>${def?.icon??'·'}</span><small>${def?.name??''}</small>${item&&item.quantity>1?`<b>${item.quantity}</b>`:''}</button>`;}).join('')}</div></section><section><h3>Equipamentos</h3><div class="equipment-list">${EQUIPMENT_SLOTS.map(slot=>`<div><small>${slotNames[slot]}</small><span>${ITEMS[d.equipment[slot]?.definitionId]?.name??'Vazio'}</span>${d.equipment[slot]?`<button data-unequip="${slot}" ${busy||blocked?'disabled':''}>Retirar</button>`:''}</div>`).join('')}</div><button data-unequip="weapon" ${busy||blocked||!d.equipment.weapon?'disabled':''}>Desequipar arma</button><div class="item-detail">${definition?`<h3>${definition.name}</h3><p>${definition.description}</p><p>${itemInfo(definition)}</p>${definition.basicAttack?`<p>Alcance básico: ${definition.basicAttack.attackRange}</p>`:''}${definition.type==='chest'?`<button class="primary-button" data-open-chest="${item.instanceId}" ${busy}>Abrir baú</button>`:`<button class="primary-button" data-equip="${this.selectedItem}" ${busy||blocked?'disabled':''}>Equipar</button>`}`:'<p>Selecione um item do inventário.</p>'}</div></section></div>`;
    }
    if(id==='skills'){
      const selected=NOVICE_TREE.find(n=>n.id===this.selectedSkill),a=ABILITIES[selected.abilityId],state=nodeState(this.character,selected);
      root.innerHTML='<p>Cinco estilos para experimentar. Aprender um caminho não bloqueia os outros. Cada nível concede um Espaço de Habilidade.</p><p><strong>Espaços de Habilidade: '+d.skillSpaces+'</strong></p><div class="novice-root">NOVATO <small>Experimente seus caminhos</small></div><div class="skill-tree">'+NOVICE_TREE.map(node=>{const a=ABILITIES[node.abilityId],state=nodeState(this.character,node);return `<button class="skill-node ${state} ${node.id===this.selectedSkill?'selected':''}" data-node="${node.id}" ${busy}><span class="item-symbol">${a.icon}</span><small>${node.branch}</small><strong>${a.name}</strong><span>${{learned:'Aprendida',available:'Disponível',locked:'Indisponível',unlearned:'Não aprendida'}[state]}</span></button>`;}).join('')+`</div><section class="skill-detail"><h3>${a.name}</h3><p>${a.description}</p><p>${a.weaponRequirements.length?'Requer '+a.weaponRequirements.map(w=>WEAPONS[w].name).join(', '):'Sem requisito de arma'} · MP ${a.manaCost} · Recarga ${a.cooldown}s${a.requiresTarget?' · Alcance '+a.range:' · Alcance: pessoal'}</p><p>Custo: ${BALANCE.skillCost} Espaço de Habilidade · Slot ${NOVICE_TREE.indexOf(selected)+1}</p>${state==='unlearned'?'<p>Você precisa de 1 Espaço de Habilidade.</p>':''}<button class="primary-button" data-learn="${a.id}" ${busy||state!=='available'?'disabled':''}>${state==='learned'?'Aprendida':'Aprender'}</button></section>`;
    }
  }
  dispose(){this.abort.abort();this.launcher.remove();Object.values(this.dialogs).forEach(d=>d.remove());}
}
